#!/ bin / sh
RET = 0

#remove useless branches
    git remote prune origin

        CHANGED = $(git diff-- cached-- name - only) if[-z $CHANGED]; then
  exit $RET
fi

#format code
echo "-- [pre-commit] Using clang-format to format code..."
for item in $CHANGED;
do
tools / clang - format - 3.8 - i - style = Google $item git add $item done
