#!/bin/bash
echo "-- [pre-commit] Preparing commit..."
RET=0

#remove useless branches
echo "-- [pre-commit] Removing useless branch..."
git remote prune origin

CHANGED_CODE=$(git diff --cached --name-only | grep -E ".h|.cpp|.cc")
if [ -z $CHANGED_CODE ]; then
  exit $RET
fi

#format code
echo "-- [pre-commit] Using clang-format to format code..."
for item in $CHANGED_CODE; do
  echo "-- [pre-commit] Formatting $item..."
  tools/clang-format-3.8 -i -style=Google $item
  git add $item
done

exit $RET
